[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT combined_app:app"
restartPolicyType = "ON_FAILURE"

[deploy.image]
repository = "shenghaoisyummy/schedule-assistant"
tag = "latest"
